-- 001-seed-general-catalogs.sql
-- Klyro general catalog seed.
-- Includes currencies, countries, phone prefixes, languages, business types and payment providers.
-- Safe to run multiple times.

\connect klyro

BEGIN;

-- =========================================================
-- Currencies
-- =========================================================

INSERT INTO currencies (code, name, symbol, is_active)
VALUES
    ('AED', 'United Arab Emirates Dirham', 'AED', true),
    ('AFN', 'Afghan Afghani', 'AFN', true),
    ('ALL', 'Albanian Lek', 'ALL', true),
    ('AMD', 'Armenian Dram', 'AMD', true),
    ('ANG', 'Netherlands Antillean Guilder', 'ANG', true),
    ('AOA', 'Angolan Kwanza', 'AOA', true),
    ('ARS', 'Argentine Peso', 'ARS', true),
    ('AUD', 'Australian Dollar', 'AUD', true),
    ('AWG', 'Aruban Florin', 'AWG', true),
    ('AZN', 'Azerbaijani Manat', 'AZN', true),
    ('BAM', 'Bosnia-Herzegovina Convertible Mark', 'BAM', true),
    ('BBD', 'Barbadian Dollar', 'BBD', true),
    ('BDT', 'Bangladeshi Taka', 'BDT', true),
    ('BGN', 'Bulgarian Lev', 'BGN', true),
    ('BHD', 'Bahraini Dinar', 'BHD', true),
    ('BIF', 'Burundian Franc', 'BIF', true),
    ('BMD', 'Bermudan Dollar', 'BMD', true),
    ('BND', 'Brunei Dollar', 'BND', true),
    ('BOB', 'Bolivian Boliviano', 'BOB', true),
    ('BRL', 'Brazilian Real', 'BRL', true),
    ('BSD', 'Bahamian Dollar', 'BSD', true),
    ('BTN', 'Bhutanese Ngultrum', 'BTN', true),
    ('BWP', 'Botswanan Pula', 'BWP', true),
    ('BYN', 'Belarusian Ruble', 'BYN', true),
    ('BZD', 'Belize Dollar', 'BZD', true),
    ('CAD', 'Canadian Dollar', 'CAD', true),
    ('CDF', 'Congolese Franc', 'CDF', true),
    ('CHF', 'Swiss Franc', 'CHF', true),
    ('CKD', 'Cook Islands Dollar', 'CKD', true),
    ('CLP', 'Chilean Peso', 'CLP', true),
    ('CNY', 'Chinese Yuan', 'CNY', true),
    ('COP', 'Colombian Peso', 'COP', true),
    ('CRC', 'Costa Rican Colon', 'CRC', true),
    ('CUC', 'Cuban Convertible Peso', 'CUC', true),
    ('CUP', 'Cuban Peso', 'CUP', true),
    ('CVE', 'Cape Verdean Escudo', 'CVE', true),
    ('CZK', 'Czech Koruna', 'CZK', true),
    ('DJF', 'Djiboutian Franc', 'DJF', true),
    ('DKK', 'Danish Krone', 'DKK', true),
    ('DOP', 'Dominican Peso', 'DOP', true),
    ('DZD', 'Algerian Dinar', 'DZD', true),
    ('EGP', 'Egyptian Pound', 'EGP', true),
    ('ERN', 'Eritrean Nakfa', 'ERN', true),
    ('ETB', 'Ethiopian Birr', 'ETB', true),
    ('EUR', 'Euro', 'EUR', true),
    ('FJD', 'Fijian Dollar', 'FJD', true),
    ('FKP', 'Falkland Islands Pound', 'FKP', true),
    ('GBP', 'British Pound', 'GBP', true),
    ('GEL', 'Georgian Lari', 'GEL', true),
    ('GHS', 'Ghanaian Cedi', 'GHS', true),
    ('GIP', 'Gibraltar Pound', 'GIP', true),
    ('GMD', 'Gambian Dalasi', 'GMD', true),
    ('GNF', 'Guinean Franc', 'GNF', true),
    ('GTQ', 'Guatemalan Quetzal', 'GTQ', true),
    ('GYD', 'Guyanaese Dollar', 'GYD', true),
    ('HKD', 'Hong Kong Dollar', 'HKD', true),
    ('HNL', 'Honduran Lempira', 'HNL', true),
    ('HRK', 'Croatian Kuna', 'HRK', true),
    ('HTG', 'Haitian Gourde', 'HTG', true),
    ('HUF', 'Hungarian Forint', 'HUF', true),
    ('IDR', 'Indonesian Rupiah', 'IDR', true),
    ('ILS', 'Israeli New Shekel', 'ILS', true),
    ('INR', 'Indian Rupee', 'INR', true),
    ('IQD', 'Iraqi Dinar', 'IQD', true),
    ('IRR', 'Iranian Rial', 'IRR', true),
    ('ISK', 'Icelandic Krona', 'ISK', true),
    ('JMD', 'Jamaican Dollar', 'JMD', true),
    ('JOD', 'Jordanian Dinar', 'JOD', true),
    ('JPY', 'Japanese Yen', 'JPY', true),
    ('KES', 'Kenyan Shilling', 'KES', true),
    ('KGS', 'Kyrgystani Som', 'KGS', true),
    ('KHR', 'Cambodian Riel', 'KHR', true),
    ('KMF', 'Comorian Franc', 'KMF', true),
    ('KPW', 'North Korean Won', 'KPW', true),
    ('KRW', 'South Korean Won', 'KRW', true),
    ('KWD', 'Kuwaiti Dinar', 'KWD', true),
    ('KYD', 'Cayman Islands Dollar', 'KYD', true),
    ('KZT', 'Kazakhstani Tenge', 'KZT', true),
    ('LAK', 'Laotian Kip', 'LAK', true),
    ('LBP', 'Lebanese Pound', 'LBP', true),
    ('LKR', 'Sri Lankan Rupee', 'LKR', true),
    ('LRD', 'Liberian Dollar', 'LRD', true),
    ('LSL', 'Lesotho Loti', 'LSL', true),
    ('LYD', 'Libyan Dinar', 'LYD', true),
    ('MAD', 'Moroccan Dirham', 'MAD', true),
    ('MDL', 'Moldovan Leu', 'MDL', true),
    ('MGA', 'Malagasy Ariary', 'MGA', true),
    ('MKD', 'Macedonian Denar', 'MKD', true),
    ('MMK', 'Myanmar Kyat', 'MMK', true),
    ('MNT', 'Mongolian Tugrik', 'MNT', true),
    ('MOP', 'Macanese Pataca', 'MOP', true),
    ('MRU', 'Mauritanian Ouguiya', 'MRU', true),
    ('MUR', 'Mauritian Rupee', 'MUR', true),
    ('MVR', 'Maldivian Rufiyaa', 'MVR', true),
    ('MWK', 'Malawian Kwacha', 'MWK', true),
    ('MXN', 'Mexican Peso', 'MXN', true),
    ('MYR', 'Malaysian Ringgit', 'MYR', true),
    ('MZN', 'Mozambican Metical', 'MZN', true),
    ('NAD', 'Namibian Dollar', 'NAD', true),
    ('NGN', 'Nigerian Naira', 'NGN', true),
    ('NIO', 'Nicaraguan Cordoba', 'NIO', true),
    ('NOK', 'Norwegian Krone', 'NOK', true),
    ('NPR', 'Nepalese Rupee', 'NPR', true),
    ('NZD', 'New Zealand Dollar', 'NZD', true),
    ('OMR', 'Omani Rial', 'OMR', true),
    ('PAB', 'Panamanian Balboa', 'PAB', true),
    ('PEN', 'Peruvian Sol', 'PEN', true),
    ('PGK', 'Papua New Guinean Kina', 'PGK', true),
    ('PHP', 'Philippine Peso', 'PHP', true),
    ('PKR', 'Pakistani Rupee', 'PKR', true),
    ('PLN', 'Polish Zloty', 'PLN', true),
    ('PYG', 'Paraguayan Guarani', 'PYG', true),
    ('QAR', 'Qatari Riyal', 'QAR', true),
    ('RON', 'Romanian Leu', 'RON', true),
    ('RSD', 'Serbian Dinar', 'RSD', true),
    ('RUB', 'Russian Ruble', 'RUB', true),
    ('RWF', 'Rwandan Franc', 'RWF', true),
    ('SAR', 'Saudi Riyal', 'SAR', true),
    ('SBD', 'Solomon Islands Dollar', 'SBD', true),
    ('SCR', 'Seychellois Rupee', 'SCR', true),
    ('SDG', 'Sudanese Pound', 'SDG', true),
    ('SEK', 'Swedish Krona', 'SEK', true),
    ('SGD', 'Singapore Dollar', 'SGD', true),
    ('SHP', 'St. Helena Pound', 'SHP', true),
    ('SLE', 'Sierra Leonean Leone', 'SLE', true),
    ('SLL', 'Sierra Leonean Leone (1964-2022)', 'SLL', true),
    ('SOS', 'Somali Shilling', 'SOS', true),
    ('SRD', 'Surinamese Dollar', 'SRD', true),
    ('SSP', 'South Sudanese Pound', 'SSP', true),
    ('STN', 'Sao Tome and Principe Dobra', 'STN', true),
    ('SVC', 'Salvadoran Colon', 'SVC', true),
    ('SYP', 'Syrian Pound', 'SYP', true),
    ('SZL', 'Swazi Lilangeni', 'SZL', true),
    ('THB', 'Thai Baht', 'THB', true),
    ('TJS', 'Tajikistani Somoni', 'TJS', true),
    ('TMT', 'Turkmenistani Manat', 'TMT', true),
    ('TND', 'Tunisian Dinar', 'TND', true),
    ('TOP', 'Tongan Paanga', 'TOP', true),
    ('TRY', 'Turkish Lira', 'TRY', true),
    ('TTD', 'Trinidad and Tobago Dollar', 'TTD', true),
    ('TWD', 'New Taiwan Dollar', 'TWD', true),
    ('TZS', 'Tanzanian Shilling', 'TZS', true),
    ('UAH', 'Ukrainian Hryvnia', 'UAH', true),
    ('UGX', 'Ugandan Shilling', 'UGX', true),
    ('USD', 'US Dollar', 'USD', true),
    ('UYU', 'Uruguayan Peso', 'UYU', true),
    ('UZS', 'Uzbekistani Som', 'UZS', true),
    ('VES', 'Venezuelan Bolivar', 'VES', true),
    ('VND', 'Vietnamese Dong', 'VND', true),
    ('VUV', 'Vanuatu Vatu', 'VUV', true),
    ('WST', 'Samoan Tala', 'WST', true),
    ('XAF', 'Central African CFA Franc', 'XAF', true),
    ('XCD', 'East Caribbean Dollar', 'XCD', true),
    ('XCG', 'Caribbean guilder', 'XCG', true),
    ('XDR', 'Special Drawing Rights', 'XDR', true),
    ('XOF', 'West African CFA Franc', 'XOF', true),
    ('XPF', 'CFP Franc', 'XPF', true),
    ('XSU', 'Sucre', 'XSU', true),
    ('XXX', 'No Currency', 'XXX', true),
    ('YER', 'Yemeni Rial', 'YER', true),
    ('ZAR', 'South African Rand', 'ZAR', true),
    ('ZMW', 'Zambian Kwacha', 'ZMW', true),
    ('ZWG', 'Zimbabwean Gold', 'ZWG', true),
    ('ZWL', 'Zimbabwean Dollar (2009-2024)', 'ZWL', true)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    symbol = EXCLUDED.symbol,
    is_active = EXCLUDED.is_active;

-- =========================================================
-- Countries
-- =========================================================

INSERT INTO countries (iso_code, name, default_currency_code, is_active)
VALUES
    ('AD', 'Andorra', 'EUR', true),
    ('AE', 'United Arab Emirates', 'AED', true),
    ('AF', 'Afghanistan', 'AFN', true),
    ('AG', 'Antigua and Barbuda', 'XCD', true),
    ('AI', 'Anguilla', 'XCD', true),
    ('AL', 'Albania', 'ALL', true),
    ('AM', 'Armenia', 'AMD', true),
    ('AO', 'Angola', 'AOA', true),
    ('AQ', 'Antarctica', 'XXX', true),
    ('AR', 'Argentina', 'ARS', true),
    ('AS', 'American Samoa', 'USD', true),
    ('AT', 'Austria', 'EUR', true),
    ('AU', 'Australia', 'AUD', true),
    ('AW', 'Aruba', 'AWG', true),
    ('AX', 'Aland Islands', 'EUR', true),
    ('AZ', 'Azerbaijan', 'AZN', true),
    ('BA', 'Bosnia and Herzegovina', 'BAM', true),
    ('BB', 'Barbados', 'BBD', true),
    ('BD', 'Bangladesh', 'BDT', true),
    ('BE', 'Belgium', 'EUR', true),
    ('BF', 'Burkina Faso', 'XOF', true),
    ('BG', 'Bulgaria', 'BGN', true),
    ('BH', 'Bahrain', 'BHD', true),
    ('BI', 'Burundi', 'BIF', true),
    ('BJ', 'Benin', 'XOF', true),
    ('BL', 'Saint Barthelemy', 'EUR', true),
    ('BM', 'Bermuda', 'BMD', true),
    ('BN', 'Brunei', 'BND', true),
    ('BO', 'Bolivia', 'BOB', true),
    ('BQ', 'Caribbean Netherlands', 'USD', true),
    ('BR', 'Brazil', 'BRL', true),
    ('BS', 'Bahamas', 'BSD', true),
    ('BT', 'Bhutan', 'BTN', true),
    ('BV', 'Bouvet Island', 'NOK', true),
    ('BW', 'Botswana', 'BWP', true),
    ('BY', 'Belarus', 'BYN', true),
    ('BZ', 'Belize', 'BZD', true),
    ('CA', 'Canada', 'CAD', true),
    ('CC', 'Cocos (Keeling) Islands', 'AUD', true),
    ('CD', 'DR Congo', 'CDF', true),
    ('CF', 'Central African Republic', 'XAF', true),
    ('CG', 'Republic of the Congo', 'XAF', true),
    ('CH', 'Switzerland', 'CHF', true),
    ('CI', 'Ivory Coast', 'XOF', true),
    ('CK', 'Cook Islands', 'CKD', true),
    ('CL', 'Chile', 'CLP', true),
    ('CM', 'Cameroon', 'XAF', true),
    ('CN', 'China', 'CNY', true),
    ('CO', 'Colombia', 'COP', true),
    ('CR', 'Costa Rica', 'CRC', true),
    ('CU', 'Cuba', 'CUC', true),
    ('CV', 'Cape Verde', 'CVE', true),
    ('CW', 'Curacao', 'ANG', true),
    ('CX', 'Christmas Island', 'AUD', true),
    ('CY', 'Cyprus', 'EUR', true),
    ('CZ', 'Czechia', 'CZK', true),
    ('DE', 'Germany', 'EUR', true),
    ('DJ', 'Djibouti', 'DJF', true),
    ('DK', 'Denmark', 'DKK', true),
    ('DM', 'Dominica', 'XCD', true),
    ('DO', 'Dominican Republic', 'DOP', true),
    ('DZ', 'Algeria', 'DZD', true),
    ('EC', 'Ecuador', 'USD', true),
    ('EE', 'Estonia', 'EUR', true),
    ('EG', 'Egypt', 'EGP', true),
    ('EH', 'Western Sahara', 'DZD', true),
    ('ER', 'Eritrea', 'ERN', true),
    ('ES', 'Spain', 'EUR', true),
    ('ET', 'Ethiopia', 'ETB', true),
    ('FI', 'Finland', 'EUR', true),
    ('FJ', 'Fiji', 'FJD', true),
    ('FK', 'Falkland Islands', 'FKP', true),
    ('FM', 'Micronesia', 'USD', true),
    ('FO', 'Faroe Islands', 'DKK', true),
    ('FR', 'France', 'EUR', true),
    ('GA', 'Gabon', 'XAF', true),
    ('GB', 'United Kingdom', 'GBP', true),
    ('GD', 'Grenada', 'XCD', true),
    ('GE', 'Georgia', 'GEL', true),
    ('GF', 'French Guiana', 'EUR', true),
    ('GG', 'Guernsey', 'GBP', true),
    ('GH', 'Ghana', 'GHS', true),
    ('GI', 'Gibraltar', 'GIP', true),
    ('GL', 'Greenland', 'DKK', true),
    ('GM', 'Gambia', 'GMD', true),
    ('GN', 'Guinea', 'GNF', true),
    ('GP', 'Guadeloupe', 'EUR', true),
    ('GQ', 'Equatorial Guinea', 'XAF', true),
    ('GR', 'Greece', 'EUR', true),
    ('GS', 'South Georgia', 'GBP', true),
    ('GT', 'Guatemala', 'GTQ', true),
    ('GU', 'Guam', 'USD', true),
    ('GW', 'Guinea-Bissau', 'XOF', true),
    ('GY', 'Guyana', 'GYD', true),
    ('HK', 'Hong Kong', 'HKD', true),
    ('HM', 'Heard Island and McDonald Islands', 'AUD', true),
    ('HN', 'Honduras', 'HNL', true),
    ('HR', 'Croatia', 'EUR', true),
    ('HT', 'Haiti', 'HTG', true),
    ('HU', 'Hungary', 'HUF', true),
    ('ID', 'Indonesia', 'IDR', true),
    ('IE', 'Ireland', 'EUR', true),
    ('IL', 'Israel', 'ILS', true),
    ('IM', 'Isle of Man', 'GBP', true),
    ('IN', 'India', 'INR', true),
    ('IO', 'British Indian Ocean Territory', 'USD', true),
    ('IQ', 'Iraq', 'IQD', true),
    ('IR', 'Iran', 'IRR', true),
    ('IS', 'Iceland', 'ISK', true),
    ('IT', 'Italy', 'EUR', true),
    ('JE', 'Jersey', 'GBP', true),
    ('JM', 'Jamaica', 'JMD', true),
    ('JO', 'Jordan', 'JOD', true),
    ('JP', 'Japan', 'JPY', true),
    ('KE', 'Kenya', 'KES', true),
    ('KG', 'Kyrgyzstan', 'KGS', true),
    ('KH', 'Cambodia', 'KHR', true),
    ('KI', 'Kiribati', 'AUD', true),
    ('KM', 'Comoros', 'KMF', true),
    ('KN', 'Saint Kitts and Nevis', 'XCD', true),
    ('KP', 'North Korea', 'KPW', true),
    ('KR', 'South Korea', 'KRW', true),
    ('KW', 'Kuwait', 'KWD', true),
    ('KY', 'Cayman Islands', 'KYD', true),
    ('KZ', 'Kazakhstan', 'KZT', true),
    ('LA', 'Laos', 'LAK', true),
    ('LB', 'Lebanon', 'LBP', true),
    ('LC', 'Saint Lucia', 'XCD', true),
    ('LI', 'Liechtenstein', 'CHF', true),
    ('LK', 'Sri Lanka', 'LKR', true),
    ('LR', 'Liberia', 'LRD', true),
    ('LS', 'Lesotho', 'LSL', true),
    ('LT', 'Lithuania', 'EUR', true),
    ('LU', 'Luxembourg', 'EUR', true),
    ('LV', 'Latvia', 'EUR', true),
    ('LY', 'Libya', 'LYD', true),
    ('MA', 'Morocco', 'MAD', true),
    ('MC', 'Monaco', 'EUR', true),
    ('MD', 'Moldova', 'MDL', true),
    ('ME', 'Montenegro', 'EUR', true),
    ('MF', 'Saint Martin', 'EUR', true),
    ('MG', 'Madagascar', 'MGA', true),
    ('MH', 'Marshall Islands', 'USD', true),
    ('MK', 'North Macedonia', 'MKD', true),
    ('ML', 'Mali', 'XOF', true),
    ('MM', 'Myanmar', 'MMK', true),
    ('MN', 'Mongolia', 'MNT', true),
    ('MO', 'Macau', 'MOP', true),
    ('MP', 'Northern Mariana Islands', 'USD', true),
    ('MQ', 'Martinique', 'EUR', true),
    ('MR', 'Mauritania', 'MRU', true),
    ('MS', 'Montserrat', 'XCD', true),
    ('MT', 'Malta', 'EUR', true),
    ('MU', 'Mauritius', 'MUR', true),
    ('MV', 'Maldives', 'MVR', true),
    ('MW', 'Malawi', 'MWK', true),
    ('MX', 'Mexico', 'MXN', true),
    ('MY', 'Malaysia', 'MYR', true),
    ('MZ', 'Mozambique', 'MZN', true),
    ('NA', 'Namibia', 'NAD', true),
    ('NC', 'New Caledonia', 'XPF', true),
    ('NE', 'Niger', 'XOF', true),
    ('NF', 'Norfolk Island', 'AUD', true),
    ('NG', 'Nigeria', 'NGN', true),
    ('NI', 'Nicaragua', 'NIO', true),
    ('NL', 'Netherlands', 'EUR', true),
    ('NO', 'Norway', 'NOK', true),
    ('NP', 'Nepal', 'NPR', true),
    ('NR', 'Nauru', 'AUD', true),
    ('NU', 'Niue', 'NZD', true),
    ('NZ', 'New Zealand', 'NZD', true),
    ('OM', 'Oman', 'OMR', true),
    ('PA', 'Panama', 'PAB', true),
    ('PE', 'Peru', 'PEN', true),
    ('PF', 'French Polynesia', 'XPF', true),
    ('PG', 'Papua New Guinea', 'PGK', true),
    ('PH', 'Philippines', 'PHP', true),
    ('PK', 'Pakistan', 'PKR', true),
    ('PL', 'Poland', 'PLN', true),
    ('PM', 'Saint Pierre and Miquelon', 'EUR', true),
    ('PN', 'Pitcairn Islands', 'NZD', true),
    ('PR', 'Puerto Rico', 'USD', true),
    ('PS', 'Palestine', 'EGP', true),
    ('PT', 'Portugal', 'EUR', true),
    ('PW', 'Palau', 'USD', true),
    ('PY', 'Paraguay', 'PYG', true),
    ('QA', 'Qatar', 'QAR', true),
    ('RE', 'Reunion', 'EUR', true),
    ('RO', 'Romania', 'RON', true),
    ('RS', 'Serbia', 'RSD', true),
    ('RU', 'Russia', 'RUB', true),
    ('RW', 'Rwanda', 'RWF', true),
    ('SA', 'Saudi Arabia', 'SAR', true),
    ('SB', 'Solomon Islands', 'SBD', true),
    ('SC', 'Seychelles', 'SCR', true),
    ('SD', 'Sudan', 'SDG', true),
    ('SE', 'Sweden', 'SEK', true),
    ('SG', 'Singapore', 'SGD', true),
    ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'GBP', true),
    ('SI', 'Slovenia', 'EUR', true),
    ('SJ', 'Svalbard and Jan Mayen', 'NOK', true),
    ('SK', 'Slovakia', 'EUR', true),
    ('SL', 'Sierra Leone', 'SLE', true),
    ('SM', 'San Marino', 'EUR', true),
    ('SN', 'Senegal', 'XOF', true),
    ('SO', 'Somalia', 'SOS', true),
    ('SR', 'Suriname', 'SRD', true),
    ('SS', 'South Sudan', 'SSP', true),
    ('ST', 'Sao Tome and Principe', 'STN', true),
    ('SV', 'El Salvador', 'USD', true),
    ('SX', 'Sint Maarten', 'ANG', true),
    ('SY', 'Syria', 'SYP', true),
    ('SZ', 'Eswatini', 'SZL', true),
    ('TC', 'Turks and Caicos Islands', 'USD', true),
    ('TD', 'Chad', 'XAF', true),
    ('TF', 'French Southern and Antarctic Lands', 'EUR', true),
    ('TG', 'Togo', 'XOF', true),
    ('TH', 'Thailand', 'THB', true),
    ('TJ', 'Tajikistan', 'TJS', true),
    ('TK', 'Tokelau', 'NZD', true),
    ('TL', 'Timor-Leste', 'USD', true),
    ('TM', 'Turkmenistan', 'TMT', true),
    ('TN', 'Tunisia', 'TND', true),
    ('TO', 'Tonga', 'TOP', true),
    ('TR', 'Turkey', 'TRY', true),
    ('TT', 'Trinidad and Tobago', 'TTD', true),
    ('TV', 'Tuvalu', 'AUD', true),
    ('TW', 'Taiwan', 'TWD', true),
    ('TZ', 'Tanzania', 'TZS', true),
    ('UA', 'Ukraine', 'UAH', true),
    ('UG', 'Uganda', 'UGX', true),
    ('UM', 'United States Minor Outlying Islands', 'USD', true),
    ('US', 'United States', 'USD', true),
    ('UY', 'Uruguay', 'UYU', true),
    ('UZ', 'Uzbekistan', 'UZS', true),
    ('VA', 'Vatican City', 'EUR', true),
    ('VC', 'Saint Vincent and the Grenadines', 'XCD', true),
    ('VE', 'Venezuela', 'VES', true),
    ('VG', 'British Virgin Islands', 'USD', true),
    ('VI', 'United States Virgin Islands', 'USD', true),
    ('VN', 'Vietnam', 'VND', true),
    ('VU', 'Vanuatu', 'VUV', true),
    ('WF', 'Wallis and Futuna', 'XPF', true),
    ('WS', 'Samoa', 'WST', true),
    ('XK', 'Kosovo', 'EUR', true),
    ('YE', 'Yemen', 'YER', true),
    ('YT', 'Mayotte', 'EUR', true),
    ('ZA', 'South Africa', 'ZAR', true),
    ('ZM', 'Zambia', 'ZMW', true),
    ('ZW', 'Zimbabwe', 'ZWL', true)
ON CONFLICT (iso_code) DO UPDATE SET
    name = EXCLUDED.name,
    default_currency_code = EXCLUDED.default_currency_code,
    is_active = EXCLUDED.is_active;

-- =========================================================
-- Phone prefixes
-- =========================================================

INSERT INTO phone_prefixes (country_id, dial_code, is_default, is_active)
SELECT c.id, v.dial_code, true, true
FROM (
    VALUES
        ('AD', '+376'),
        ('AE', '+971'),
        ('AF', '+93'),
        ('AG', '+1'),
        ('AI', '+1'),
        ('AL', '+355'),
        ('AM', '+374'),
        ('AO', '+244'),
        ('AR', '+54'),
        ('AS', '+1'),
        ('AT', '+43'),
        ('AU', '+61'),
        ('AW', '+297'),
        ('AX', '+358'),
        ('AZ', '+994'),
        ('BA', '+387'),
        ('BB', '+1'),
        ('BD', '+880'),
        ('BE', '+32'),
        ('BF', '+226'),
        ('BG', '+359'),
        ('BH', '+973'),
        ('BI', '+257'),
        ('BJ', '+229'),
        ('BL', '+590'),
        ('BM', '+1'),
        ('BN', '+673'),
        ('BO', '+591'),
        ('BQ', '+599'),
        ('BR', '+55'),
        ('BS', '+1'),
        ('BT', '+975'),
        ('BV', '+47'),
        ('BW', '+267'),
        ('BY', '+375'),
        ('BZ', '+501'),
        ('CA', '+1'),
        ('CC', '+61'),
        ('CD', '+243'),
        ('CF', '+236'),
        ('CG', '+242'),
        ('CH', '+41'),
        ('CI', '+225'),
        ('CK', '+682'),
        ('CL', '+56'),
        ('CM', '+237'),
        ('CN', '+86'),
        ('CO', '+57'),
        ('CR', '+506'),
        ('CU', '+53'),
        ('CV', '+238'),
        ('CW', '+599'),
        ('CX', '+61'),
        ('CY', '+357'),
        ('CZ', '+420'),
        ('DE', '+49'),
        ('DJ', '+253'),
        ('DK', '+45'),
        ('DM', '+1'),
        ('DO', '+1'),
        ('DZ', '+213'),
        ('EC', '+593'),
        ('EE', '+372'),
        ('EG', '+20'),
        ('EH', '+212'),
        ('ER', '+291'),
        ('ES', '+34'),
        ('ET', '+251'),
        ('FI', '+358'),
        ('FJ', '+679'),
        ('FK', '+500'),
        ('FM', '+691'),
        ('FO', '+298'),
        ('FR', '+33'),
        ('GA', '+241'),
        ('GB', '+44'),
        ('GD', '+1'),
        ('GE', '+995'),
        ('GF', '+594'),
        ('GG', '+44'),
        ('GH', '+233'),
        ('GI', '+350'),
        ('GL', '+299'),
        ('GM', '+220'),
        ('GN', '+224'),
        ('GP', '+590'),
        ('GQ', '+240'),
        ('GR', '+30'),
        ('GS', '+500'),
        ('GT', '+502'),
        ('GU', '+1'),
        ('GW', '+245'),
        ('GY', '+592'),
        ('HK', '+852'),
        ('HN', '+504'),
        ('HR', '+385'),
        ('HT', '+509'),
        ('HU', '+36'),
        ('ID', '+62'),
        ('IE', '+353'),
        ('IL', '+972'),
        ('IM', '+44'),
        ('IN', '+91'),
        ('IO', '+246'),
        ('IQ', '+964'),
        ('IR', '+98'),
        ('IS', '+354'),
        ('IT', '+39'),
        ('JE', '+44'),
        ('JM', '+1'),
        ('JO', '+962'),
        ('JP', '+81'),
        ('KE', '+254'),
        ('KG', '+996'),
        ('KH', '+855'),
        ('KI', '+686'),
        ('KM', '+269'),
        ('KN', '+1'),
        ('KP', '+850'),
        ('KR', '+82'),
        ('KW', '+965'),
        ('KY', '+1'),
        ('KZ', '+7'),
        ('LA', '+856'),
        ('LB', '+961'),
        ('LC', '+1'),
        ('LI', '+423'),
        ('LK', '+94'),
        ('LR', '+231'),
        ('LS', '+266'),
        ('LT', '+370'),
        ('LU', '+352'),
        ('LV', '+371'),
        ('LY', '+218'),
        ('MA', '+212'),
        ('MC', '+377'),
        ('MD', '+373'),
        ('ME', '+382'),
        ('MF', '+590'),
        ('MG', '+261'),
        ('MH', '+692'),
        ('MK', '+389'),
        ('ML', '+223'),
        ('MM', '+95'),
        ('MN', '+976'),
        ('MO', '+853'),
        ('MP', '+1'),
        ('MQ', '+596'),
        ('MR', '+222'),
        ('MS', '+1'),
        ('MT', '+356'),
        ('MU', '+230'),
        ('MV', '+960'),
        ('MW', '+265'),
        ('MX', '+52'),
        ('MY', '+60'),
        ('MZ', '+258'),
        ('NA', '+264'),
        ('NC', '+687'),
        ('NE', '+227'),
        ('NF', '+672'),
        ('NG', '+234'),
        ('NI', '+505'),
        ('NL', '+31'),
        ('NO', '+47'),
        ('NP', '+977'),
        ('NR', '+674'),
        ('NU', '+683'),
        ('NZ', '+64'),
        ('OM', '+968'),
        ('PA', '+507'),
        ('PE', '+51'),
        ('PF', '+689'),
        ('PG', '+675'),
        ('PH', '+63'),
        ('PK', '+92'),
        ('PL', '+48'),
        ('PM', '+508'),
        ('PN', '+64'),
        ('PR', '+1'),
        ('PS', '+970'),
        ('PT', '+351'),
        ('PW', '+680'),
        ('PY', '+595'),
        ('QA', '+974'),
        ('RE', '+262'),
        ('RO', '+40'),
        ('RS', '+381'),
        ('RU', '+7'),
        ('RW', '+250'),
        ('SA', '+966'),
        ('SB', '+677'),
        ('SC', '+248'),
        ('SD', '+249'),
        ('SE', '+46'),
        ('SG', '+65'),
        ('SH', '+290'),
        ('SI', '+386'),
        ('SJ', '+47'),
        ('SK', '+421'),
        ('SL', '+232'),
        ('SM', '+378'),
        ('SN', '+221'),
        ('SO', '+252'),
        ('SR', '+597'),
        ('SS', '+211'),
        ('ST', '+239'),
        ('SV', '+503'),
        ('SX', '+1'),
        ('SY', '+963'),
        ('SZ', '+268'),
        ('TC', '+1'),
        ('TD', '+235'),
        ('TF', '+262'),
        ('TG', '+228'),
        ('TH', '+66'),
        ('TJ', '+992'),
        ('TK', '+690'),
        ('TL', '+670'),
        ('TM', '+993'),
        ('TN', '+216'),
        ('TO', '+676'),
        ('TR', '+90'),
        ('TT', '+1'),
        ('TV', '+688'),
        ('TW', '+886'),
        ('TZ', '+255'),
        ('UA', '+380'),
        ('UG', '+256'),
        ('UM', '+1'),
        ('US', '+1'),
        ('UY', '+598'),
        ('UZ', '+998'),
        ('VA', '+39'),
        ('VC', '+1'),
        ('VE', '+58'),
        ('VG', '+1'),
        ('VI', '+1'),
        ('VN', '+84'),
        ('VU', '+678'),
        ('WF', '+681'),
        ('WS', '+685'),
        ('XK', '+383'),
        ('YE', '+967'),
        ('YT', '+262'),
        ('ZA', '+27'),
        ('ZM', '+260'),
        ('ZW', '+263')
) AS v(iso_code, dial_code)
JOIN countries c ON c.iso_code = v.iso_code
ON CONFLICT (country_id, dial_code) DO UPDATE SET
    is_default = EXCLUDED.is_default,
    is_active = EXCLUDED.is_active;

-- =========================================================
-- Languages
-- =========================================================

INSERT INTO languages (code, name, native_name, is_active)
VALUES
    ('es', 'Spanish', 'Español', true),
    ('en', 'English', 'English', true),
    ('fr', 'French', 'Français', true),
    ('de', 'German', 'Deutsch', true),
    ('pt', 'Portuguese', 'Português', true),
    ('it', 'Italian', 'Italiano', true)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    native_name = EXCLUDED.native_name,
    is_active = EXCLUDED.is_active;

-- =========================================================
-- Business types
-- =========================================================

INSERT INTO business_types (code, name, description, is_active)
VALUES
    ('barbershop', 'Barbershop', 'Business focused on haircuts, beard trims and grooming services.', true),
    ('salon', 'Hair Salon', 'Business focused on hair, beauty, styling and related appointment-based services.', true),
    ('tutoring', 'Tutoring Center', 'Business or professional service that schedules classes, tutoring sessions or academic support.', true),
    ('clinic', 'Clinic', 'Small clinic or healthcare-related appointment-based business.', true),
    ('dental', 'Dental Clinic', 'Dental office or dentist that schedules patient appointments.', true),
    ('spa', 'Spa', 'Business that schedules wellness, massage, facial or relaxation services.', true),
    ('fitness', 'Fitness Coach', 'Personal trainer, coach or fitness-related appointment-based service.', true),
    ('consulting', 'Consulting', 'Professional consulting business that schedules sessions or meetings.', true),
    ('other', 'Other', 'Generic appointment-based business type.', true)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description,
    is_active = EXCLUDED.is_active;

-- =========================================================
-- Payment providers
-- =========================================================

INSERT INTO payment_providers (code, name, is_active)
VALUES
    ('free', 'Free/Internal', true),
    ('manual', 'Manual', true),
    ('lemonsqueezy', 'Lemon Squeezy', true)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    is_active = EXCLUDED.is_active;

COMMIT;
